### ISSUE TITLE
release on hex.pm?

### ISSUE THREAD

**Issue by benoitc** [rabbitmq/aten#11]
I wonder that now the project is stable enough if you could tag a release and publish it on aten? Unfortunately hex doesn't allow to mix hex and git dependency :/

**Comment by kjnilsson** [comment]
We have a TODO somewhere to do that for `aten` and Ra but not got around to do it yet. Will try to take a look at it again this week.

**Comment by kjnilsson** [comment]
This is now done: https://hex.pm/packages/aten
