### ISSUE TITLE
Consider emitting "node up" events for connected ("known") newly registered nodes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/aten#23]
We currently emit a "node down" event followed by a "node up" for newly registered nodes (#13, https://github.com/rabbitmq/aten/commit/634f9a00b4b74de880d834fdce6d8d541bec858a). #21 and #22 make me wonder if it should be a "node up" event only.

**Comment by kjnilsson** [comment]
This scenario would only happen during a small window when the registration request was processed after a new node connected but before the new node has emitted a heartbeat. As aten should only operate on the state of heartbeats this should not be needed as explained in #22 

Listening processes could wait an aten poll interval before taking any action based on a received down event.
