### ISSUE TITLE
Should nodes recover connections automatically?

### ISSUE THREAD

**Issue by benoitc** [rabbitmq/aten#6]
I was looking at the code and I am wondering about the requirements. 

As I understand it it first try to connect on register but there doesn't seems to have any any reconnection planned when the node is down.  What should we do then when the node is down? Forcing a reconnect? I am thinking that since you force the connection on first call you may want to reconnect it as well, thoughts?

**Comment by kjnilsson** [comment]
Yes we did consider reconnections a but in the end left it to the consuming
applications to reconnect themselves. I might have to review that code but
the idea with a separation between cluster membership and registrations is
to allow nodes to come and go without aten having to try to maintain some
kind of master membership list.

**Comment by kjnilsson** [comment]
I've removed the code that performs the connection attempt on registration. This means the sole responsibility of aten is to detect when nodes come and (potentially) go and report this status to interested processes. I think things like maintaining an erlang cluster should be the responsibility of a separate component.

Closing this - please re-open if there is anything else to address.
